service: user-management-service

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

	
useDotenv: true

provider:
  name: aws 
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 1024

environment:
  MONGO_URL: ${env:MONGO_URL}
  PORT: ${env:PORT}

functions:
  signup:
    name: user-management-signup-${self:provider.stage}
    handler: src/handlers/account/index.handler
    events:
      - http:
          path: /signup
          method: POST
          cors: true
          